# Bevezetés {#Chapter-1}

```{css, echo=FALSE}
p {
text-align: justify;
  }
```

A hozamgörbék recesszió előrejelző képességét az 1980-as évek végén kezdték el vizsgálni [pl. Keen, 1989; Stevens, 1989] , a '90-es évek végére pedig komoly szakirodalma lett a témának. Ezek a tanulmányok azt vizsgálják, hogy a különböző lejáratú államkötvények hozamainak különbsége időben hogyan alakul, illetve hogy ez a különbség milyen kapcsolatban áll a reálgazdaság teljesítményével. Az empíria azt mutatja, hogy a gazdasági visszaeséseket a hozamgörbék invertálódása előzi meg, ami azt jelenti, hogy a rövid lejáratú állampapírok hozamai magasabbak, mint a hosszú lejáratú állampapíroké, tehát a hozamszpred negatív tartományba kerül. Ekkor tehát a befektetők a rövid távú befektetéseket kockázatosabbnak ítélik meg, mint a hosszú távú befektetéseket, ami ellent mond az általános gazdasági viselkedésnek. Két tipikus elemzés terjedt el: (1) a GDP növekedési rátájának kvantitatív előrejelzése folytonos modellekkel, (2) a recessziók valószínűségének előrejelzése bináris modellekkel. Estrella és szerzőtársai [2003] azt találják, hogy az utóbbi típusú elemzések jobban teljesítenek.

Estrella és Fishkin [1996] egy rövid tanulmányukban amellett érvelnek, hogy a hozamszpredek többek között azért is jó indikátorok, mivel a monetáris politikának erős hatása van rá, és így ezen keresztül a reálgazdaságot is képes lehet befolyásolni. Emellett a hozamszpredek tartalmazzák az inflációs és a kamatlábra vonatkozó várakozásokat is, amelynek szintén fontos szerepet tulajdonítanak a szerzők. Ugyanez a szerzőpáros [Estrella & Mishkin, 1998] egy hosszabb tanulmányukban pénzügyi indikátorok, köztük különböző kamatlábak, részvényárak, monetáris aggregátumok és a hozamszpred előrejelző képességét vizsgálták probit modellek segítségével. Azt találták, hogy míg 1-3 negyedéves időhorizonton a részvényárak és a monetáris aggregátumok egyaránt jól jeleznek előre a mintán kívül, addig az ennél távolibb időpontokra való előrejelzésben egyértelműen a hozamszpred emelkedik ki, és jellemzően önmagában, tehát minden más változó bevonása nélkül teljesít jól. Wright [2006] ezzel ellentétes következtetésre jut, tanulmányában megállapítja, hogy a hozamszpredek önmagukban kevésbé jól jeleznek előre recessziót, mint amikor a modell külön változóként a hozamokat is tartalmazza.

Érdekesség azonban, hogy az előbb idézett tanulmány alapján az utóbbi modellek 2006-ban nem jeleztek előre recessziót, míg a hozamszpredek önmagukban igen. Wright a többváltozós modellnek hitt, később kiderült, hogy tévedett. A 2007-2009-es válságot megelőzően a Federal Reserve egy másik elemzője, Haubrich [2005] is arra a végső következtetésre jut cikkében, hogy nem valószínű, hogy a csökkenő hozamszpredek recessziót jeleznek előre.

A Nagy Recessziót követő időszakban számos további tanulmány született a témában [pl. Rudebusch & Williams, 2009; Chinn & Kucko, 2010], 2017-től pedig ismét laposodott az amerikai hozamgörbe. Bauer és Mertens [2018a] tanulmányukban megállapítják, hogy a hozamszpred kritikus határértéke a 0, tehát egy 0-hoz közeli, de pozitív érték még nem ad okot aggodalomra, viszont a negatív hozamgörbe már vészjósló jelenség. A szerzőpáros amellett érvelt, hogy mivel a pénzügyi válság utáni időszakot amúgy is egy alacsony kamat- és hozamkörnyezet jellemezte, ami történelmi összehasonlításban is különös jelenség, nem vonható le messzemenő következtetés a hozamszpredek alakulása alapján.

2019 elején már sorra írták meg a különböző sajtóorgánumok is, köztük a Forbes, illetve a Bloomberg, hogy az amerikai hozamgörbe laposodik, és csak idő kérdése, hogy inverz hozamgörbéről beszéljünk, ami pedig egy közelgő recesszió gyanúját keltette a közgazdászokban. 2019 augusztusában az amerikai hosszú és rövid távú állampapírhozamok különbsége negatív értéket vett fel [FRED, 2021], a prognosztizált pénzügyi válság helyett azonban a koronavírus járvány következtében nézhettünk, illetve nézhetünk szembe egy komoly gazdasági visszaeséssel. Ez a jelenség sokféle spekulációnak és konspirációs elméletnek adott teret, és sok emberben felmerült a kérdés, hogy csupán egy véletlen egybeeséssel nézünk-e szembe.

Chauvet és Potter [2005] tanulmányukban a standard probit modell előrejelző képességét hasonlították össze szofisztikáltabb, kiterjesztett probit modellekével. Az utóbbiak jellemzően hatékonyabban jeleztek előre a mintán kívül, azonban egyedül a standard modell jósolt recessziót 2001 végére a 2001 márciusáig rendelkezésre álló információk alapján. A szerzők amellett érvelnek, hogy ez alapján téves lenne azt a következtetést levonni, miszerint a standard modell jobban teljesít, hiszen a modell rendelkezésére álló információk nem tartalmazták az év szeptember 11-i eseményeit, az Egyesült Államokat ért terrortámadást, ami pedig jelentősen hozzájárult a 2001-es gazdasági visszaeséshez. Nehéz lenne megmondani, hogy ez a kijelentésük magától értetődő-e, ahogy azt is, hogy a 2019-es hozamgörbék előrejelezhették-e egy világméretű egészségügyi járvány gazdasági hatásait, mindenesetre a hozamszpredek kérdése töretlen erővel nyújt ihletet a közgazdászoknak.
